[package]
name = "py-rattler"
version = "0.8.2"
edition = "2021"
license = "BSD-3-Clause"
publish = false

[lib]
name = "rattler"
crate-type = ["cdylib"]

[features]
default = ["rustls-tls"]
native-tls = [
    "rattler_networking/native-tls",
    "rattler_repodata_gateway/native-tls",
]
rustls-tls = [
    "rattler_networking/rustls-tls",
    "rattler_repodata_gateway/rustls-tls",
    "reqwest/rustls-tls-native-roots",
]
vendored-openssl = ["openssl", "openssl/vendored"]

[dependencies]
anyhow = "1.0.92"
chrono = { version = "0.4" }
futures = "0.3.31"

rattler = { version = "0.28.4", default-features = false, features = [
    "indicatif",
] }
rattler_repodata_gateway = { version = "0.21.24", default-features = false, features = [
    "sparse",
    "gateway",
] }
rattler_conda_types = { version="0.29.3", default-features = false }
rattler_digest = { version="1.0.3" }
rattler_networking = { version = "0.21.7", default-features = false, features = [
    "gcs",
] }
rattler_shell = { version = "0.22.8", default-features = false }
rattler_virtual_packages = { version="1.1.11", default-features = false }
rattler_solve = { version="1.2.4", default-features = false, features = [
    "resolvo",
] }
rattler_index = { version="0.19.37" }
rattler_lock = { version="0.22.32", default-features = false }
rattler_package_streaming = { version="0.22.15", default-features = false }
pyo3 = { version = "0.22.5", features = [
    "abi3-py38",
    "extension-module",
    "multiple-pymethods",
    "chrono",
    "gil-refs",
] }
pyo3-async-runtimes = { version = "0.22.0", features = ["tokio-runtime"] }
tokio = { version = "1.41" }

reqwest = { version = "0.12.9", default-features = false }
reqwest-middleware = "0.4.0"

thiserror = "1.0.67"
url = "2.5.3"

openssl = { version = "0.10", optional = true }
pep508_rs = "0.9.1"
serde_json = "1.0.132"
pyo3-file = "0.9.0"

[build-dependencies]
pyo3-build-config = "0.22.5"


[patch.crates-io]

# Prevent package from thinking it's in the workspace
[workspace]
