[workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

#
# Package section
#
# This defines the package metadata, build-system and dependencies
#

[package]
name = "py-rattler"
version = "0.8.2"
description = "Add a short description here"
authors = [
    "Bas Zalmstra <bas@prefix.dev>",
    "Tarun Pratap Singh <pratapsinghtarun9@gmail.com>",
]
license = "BSD-3-Clause"

[build-system]
build-backend = { name = "pixi-build-python", version = "*" }
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]

[build-backend.pixi-build-python]
# py-rattler is an arch specific package.
noarch = false

[host-dependencies]
maturin = "~=1.7.7"
rust = "~=1.81.0"
uv = "*"

[target.linux-64.dependencies]
patchelf = "~=0.17.2"

[feature.build.dependencies]
py-rattler = { path = "." }


[tasks]

[feature.test.dependencies]
# Python 3.8 is the minimum supported version, so we use that for testing
python = "3.9.*"

ruff = ">=0.3.3,<0.4"
mypy = "~=1.5.1"

pytest = "~=7.4.0"
pytest-asyncio = "0.21.1.*"
pytest-xprocess = ">=0.23.0,<0.24"

# used in examples
typer = "*"

[feature.test.pypi-dependencies]
types-networkx = "*"

[feature.test.tasks]
test = { cmd = "pytest --doctest-modules" }
fmt-python = "ruff format rattler examples tests"
fmt-rust = "cargo fmt --all"
lint-python = "ruff check ."
lint-rust = "cargo clippy --all"
fmt = { depends_on = ["fmt-python", "fmt-rust"] }
lint = { depends_on = ["type-check", "lint-python", "lint-rust"] }
type-check = { cmd = "mypy" }

# checks for the CI
fmt-rust-check = "cargo fmt --all --check"
fmt-python-check = "ruff format rattler examples tests --diff"
fmt-check = { depends_on = ["fmt-python-check", "fmt-rust-check"] }

[feature.docs.dependencies]
mkdocs = ">=1.5.3,<2"
mkdocstrings-python = ">=1.9.0,<2"
mkdocstrings = ">=0.24.1,<1"
mkdocs-material = ">=9.5.20"
mdx_truly_sane_lists = ">=1.3,<2"
cairosvg = "2.7.1.*"
pillow = ">=9.4.0"

[feature.docs.tasks]
docs = { cmd = "mkdocs serve" }
build-docs = { cmd = "mkdocs build" }

[feature.repl.dependencies]
ipython = ">=8.29.0,<9"
[feature.repl.tasks]
repl = { depends-on = ["build"], cmd = "ipython" }

[environments]
#build = { features = ["build"], solve-group = "default" }
test = { features = ["build", "test"], solve-group = "default" }
docs = ["docs"]
repl = ["repl"]

[dependencies]
requests = ">=2.32.3,<2.33"
types-requests = ">=2.32.0.20240602,<2.32.1"
